# 工作流名称
name: Sync-Images-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "master" ]

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4

    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Personal Registry
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        #!/usr/bin/env bash
        set -o pipefail
        sudo jq '. + {"insecure-registries": ["http://docker.sgwbox.com:5001"]}' /etc/docker/daemon.json  > temp.json && sudo mv temp.json /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 3
        sudo docker login docker.sgwbox.com:5001 -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
        sudo skopeo copy docker://docker.io/gngpp/xunlei:latest docker://docker.sgwbox.com:5001/gngpp/xunlei:latest --override-arch arm64 --dest-tls-verify=false
        sudo docker logout docker.sgwbox.com:5001
    
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
