# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/xiaoyaliu/alist:latest docker://nat671.yyboxdns.com:15287/alist:latest --override-arch arm64 --dest-tls-verify=false
        skopeo copy docker://docker.io/sulinggg/openwrt-mini:armv8 docker://nat671.yyboxdns.com:15287/openwrt-mini:armv8 --override-arch arm64 --dest-tls-verify=false
